import { array } from './array'
import { boolean } from './boolean'
import { checkboxGroup } from './checkbox-group'
import { color } from './color'
import { date, today } from './date'
import { datetime } from './datetime'
import { duration } from './duration'
import { email } from './email'
import { image } from './image'
import { masked } from './masked'
import { mediaPlayer } from './media-player'
import { money } from './money'
import { number } from './number'
import { phone } from './phone'
import { radio } from './radio'
import { richText } from './rich-text'
import { section } from './section'
import { seo } from './seo'
import { select } from './select'
import { slug } from './slug'
import { string } from './string'
import { tags } from './tags'
import { tab } from './tab'
import { textarea } from './textarea'
import { url } from './url'

export const field = { string, masked, slug, email, phone, url, mediaPlayer, textarea, richText, number, money, boolean, image, select, radio, checkboxGroup, tags, date, datetime, duration, color, array, section, seo, tab }
export { today }
export { toMs } from '../utils/duration'
